# Generated by Django 3.1.3 on 2020-11-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_article_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='news_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.article'),
        ),
    ]
