# Generated by Django 3.1.3 on 2020-11-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_slider_news_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_picture',
            field=models.ImageField(blank=True, null=True, upload_to='slider_pics/'),
        ),
    ]
