# Generated by Django 3.1.3 on 2020-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_slider_slider_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
