# Generated by Django 3.1.3 on 2020-11-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_article_make_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='make_slider',
        ),
    ]
