# Generated by Django 3.1.3 on 2020-11-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_article_make_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=130, null=True, unique=True),
        ),
    ]
