# Generated by Django 3.1.3 on 2020-11-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_article_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
