# Generated by Django 3.1.3 on 2020-11-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_newspost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(to='posts.Tag'),
        ),
    ]
