# Generated by Django 3.1.3 on 2020-11-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
