# Generated by Django 3.1.3 on 2020-11-30 11:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_slider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='news/pictures/'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='publishable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='slider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.slider'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=130, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='article/pictures/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='article/thumbnails/'),
        ),
    ]
