# Generated by Django 3.1.3 on 2020-11-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20201130_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
