# Generated by Django 3.1.3 on 2020-12-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_newspost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='date_as_day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
