# Generated by Django 3.1.3 on 2020-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20201202_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_type',
            field=models.CharField(choices=[('Article', 'ARTICLE'), ('NewsPost', 'NEWS')], default='ARTICLE', max_length=20),
        ),
    ]
