# Generated by Django 3.1.3 on 2020-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20201202_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title2',
        ),
        migrations.AlterField(
            model_name='postitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='posts/pictures/'),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='post_type',
            field=models.CharField(choices=[('Article', 'Article'), ('News', 'News')], default='ARTICLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/thumbnails/'),
        ),
    ]
