# Generated by Django 3.1.3 on 2020-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
    ]
