# Generated by Django 3.1.3 on 2021-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_postitem_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postitem',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='postitem',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
