# Generated by Django 3.1.3 on 2021-01-14 11:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_slider_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='color2',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
