# Generated by Django 3.1.3 on 2021-01-14 11:55

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_postitem_color2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postitem',
            name='color2',
        ),
        migrations.AlterField(
            model_name='postitem',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
