# Generated by Django 3.1.3 on 2021-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_slider_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='site_url',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
