# Generated by Django 3.1.3 on 2020-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201120_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linked_In_URL',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
